backend/src/main/java/com/hummerrisk/service/CloudEventService.java
=> feat(cloudEvent):修改华为方法参数

backend/pom.xml, backend/src/main/java/com/hummerrisk/service/CloudEventService.java
=> feat(cloudEvent):修改aliyun sdk包

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtAccountMapper.xml
=> fix(account):解决调参列表无数据问题

backend/src/main/resources/db/migration/V28__alert_cloud_event.sql
=> fix(flyway):cloud_event添加username字段

backend/src/main/java/com/hummerrisk/service/ImageService.java
=> fix(image):新增获取 harbor image 列表方法

backend/src/main/java/com/hummerrisk/service/ImageService.java
=> feat(image):修改获取 harbor image 列表方法

backend/src/main/resources/db/migration/V29__init_image_repo_item.sql
=> feat(flyway):新增 image_repo_item

backend/src/main/java/com/hummerrisk/service/ImageService.java
=> feat(image):修改获取镜像代码

backend/src/main/java/com/hummerrisk/service/ImageService.java
=> feat(image):修改镜像获取

backend/src/main/java/com/hummerrisk/controller/CloudEventController.java, backend/src/main/java/com/hummerrisk/service/CloudEventService.java, frontend/src/business/components/log/home/sync.vue
=> feat(event):解决数据量过大报错问题

backend/src/main/java/com/hummerrisk/service/CloudEventService.java, frontend/src/business/components/log/head/TableHeader.vue, frontend/src/business/components/log/home/event.vue
=> feat(event):事件支持多区域查询

frontend/src/business/components/log/home/event.vue
=> feat(event):前端事件列表修改

backend/src/main/resources/db/migration/V32__init_cloud_event_region_log.sql
=> feat(flyway):主机规则新增标签

frontend/src/business/components/log/home/sync.vue
=> fix(event):点击同步时清空表单

backend/pom.xml, backend/src/main/java/com/hummerrisk/service/CloudEventService.java
=> fix(event):后端新增华为事件同步

backend/src/main/resources/db/migration/V33__alter_cloud_event.sql
=> feat(flyway):云事件增加字段

frontend/src/business/components/report/home/List.vue
=> fix(cloudReport):解决规则详情里规则组展示不正确问题

backend/src/main/resources/db/migration/V33__alter_cloud_event.sql
=> feat(flyway):修改云事件

backend/src/main/java/com/hummerrisk/service/CloudEventService.java
=> feat(cloudEvent):解决报错

backend/src/main/java/com/hummerrisk/service/CloudEventService.java, frontend/src/business/components/log/home/sync.vue
=> feat(cloudEvent):异常错误日志

frontend/src/business/components/log/home/Regions.vue, frontend/src/business/components/log/home/event.vue
=> fix(event):解决点击同步数量与事件内容不一致问题

backend/src/main/resources/db/migration/V34__add_rule.sql
=> feat(flyway):新增UCloud规则

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudEventMapper.xml, backend/src/main/java/com/hummerrisk/service/CloudEventService.java, frontend/src/business/components/common/components/search/search-components.js, frontend/src/business/components/log/home/event.vue, frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
=> feat(event):修改过滤条件

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtRuleGroupMapper.java, backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtRuleGroupMapper.xml, backend/src/main/java/com/hummerrisk/service/RuleService.java
=> fix(rule):解决分组检测重复检测问题

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudResourceItemMapper.xml, frontend/src/business/components/cloudSituation/home/ResultReadOnly.vue, frontend/src/business/components/cloudSituation/home/SourceList.vue, frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
=> feat(resource):修改cloud resource

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudEventMapper.java, backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudEventMapper.xml, backend/src/main/java/com/hummerrisk/controller/CloudEventController.java, backend/src/main/java/com/hummerrisk/dto/CloudEventGroupDTO.java, backend/src/main/java/com/hummerrisk/service/CloudEventService.java, frontend/src/business/components/common/components/search/search-components.js, frontend/src/business/components/event/home/Group.vue, frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
=> feat(event):云事件聚合

backend/src/main/java/com/hummerrisk/service/CloudEventService.java, frontend/src/business/components/event/home/Group.vue
=> feat(event):事件去重

backend/src/main/resources/db/migration/V34__add_rule.sql
=> feat(flyway):事件增加主键，添加aliyun规则

backend/src/main/java/com/hummerrisk/commons/constants/CloudTaskConstants.java
=> feat(resource):增加资源类型

backend/src/main/java/com/hummerrisk/commons/constants/CloudTaskConstants.java, backend/src/main/java/com/hummerrisk/service/CloudSyncService.java, frontend/src/business/components/cloudSituation/home/ResultLog.vue
=> feat(resource):修改资源同步

frontend/src/business/components/cloudSituation/home/SourceList.vue, frontend/src/business/components/common/components/search/search-components.js
=> fix(resource):解决点击分页过滤条件失效问题

frontend/src/business/components/cloudSituation/home/CloudSyncLog.vue, frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
=> feat(resource):增加重新同步按钮

frontend/src/business/components/cloudSituation/home/ResultLog.vue
=> feat(resource):修改日志显示

frontend/src/business/components/cloudSituation/home/CloudSyncLog.vue, frontend/src/business/components/cloudSituation/home/SourceList.vue
=> feat(resource):资源列表数据列调整

backend/src/main/java/com/hummerrisk/service/CloudTaskService.java, backend/src/main/java/com/hummerrisk/service/OrderService.java
=> feat(task):增加资源总数统计

frontend/src/business/components/cloudSituation/home/CloudSyncLog.vue, frontend/src/business/components/cloudSituation/home/SourceList.vue
=> feat(resource):修改资源列表

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudResourceItemMapper.xml
=> feat(resource):增加排序

backend/src/main/java/com/hummerrisk/commons/utils/PlatformUtils.java, frontend/src/business/components/cloudSituation/home/CloudSyncLog.vue
=> feat(resource):增加不支持区域

backend/src/main/java/com/hummerrisk/service/CloudEventService.java
=> feat(event):腾讯增加事件过滤

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudResourceItemMapper.java, backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudResourceItemMapper.xml, backend/src/main/java/com/hummerrisk/controller/CloudResourceController.java, backend/src/main/java/com/hummerrisk/dto/CloudResourceItemDTO.java, backend/src/main/java/com/hummerrisk/dto/ResourceRuleDTO.java, backend/src/main/java/com/hummerrisk/service/CloudResourceService.java, frontend/src/business/components/cloudSituation/home/ResourceRule.vue, frontend/src/business/components/cloudSituation/home/SourceList.vue, frontend/src/business/components/event/home/Event.vue, frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
=> feat(resource):资源关联扫描结果

backend/src/main/java/com/hummerrisk/service/CloudSyncService.java
=> feat(resource):填补空缺字段

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudResourceItemMapper.java, backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudResourceItemMapper.xml, backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudTaskMapper.java, backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudTaskMapper.xml, backend/src/main/java/com/hummerrisk/controller/CloudResourceController.java, backend/src/main/java/com/hummerrisk/dto/CloudResourceItemDTO.java, backend/src/main/java/com/hummerrisk/service/CloudResourceService.java, frontend/src/business/components/cloudSituation/home/ResourceRule.vue, frontend/src/business/components/cloudSituation/home/SourceList.vue, frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
=> feat(resource):修改风险关联

frontend/src/business/components/cloudSituation/home/ResourceRule.vue, frontend/src/business/components/cloudSituation/home/SourceList.vue, frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
=> feat(resource):修改风险关联前端

backend/src/main/java/com/hummerrisk/service/OrderService.java
=> fix(云检测):解决资源总数不对

backend/src/main/java/com/hummerrisk/service/ResourceCreateService.java
=> fix(云检测):解决policy.yml重复写入问题

backend/pom.xml, backend/src/main/java/com/hummerrisk/service/CloudEventService.java
=> feat(cloudEvent):新增AWS

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudTaskMapper.java, backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudTaskMapper.xml, backend/src/main/java/com/hummerrisk/controller/CloudResourceController.java, backend/src/main/java/com/hummerrisk/service/CloudEventService.java, backend/src/main/java/com/hummerrisk/service/CloudResourceService.java, frontend/src/business/components/cloudSituation/home/ResourceRule.vue
=> feat(cloudResource):解决风险重复问题

backend/pom.xml, backend/src/main/java/com/hummerrisk/oss/provider/QingcloudProvider.java
=> feat(oss):新增青云

backend/src/main/java/com/hummerrisk/oss/provider/QiniuProvider.java, backend/src/main/java/com/hummerrisk/proxy/qiniu/QiniuCredential.java
=> feat(oss):新增七牛

backend/src/main/resources/db/migration/V38__alter_oss.sql
=> feat(flyway):新增 aliyun 规则

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudResourceItemMapper.xml, backend/src/main/java/com/hummerrisk/service/CloudEventService.java
=> feat(resource):解决删除账号后依然显示资源问题

backend/src/main/java/com/hummerrisk/oss/provider/QiniuProvider.java
=> feat(qiniu):获取bucket region，修改 object 更新时间显示不对bug

backend/pom.xml, backend/src/main/java/com/hummerrisk/oss/provider/UcloudProvider.java
=> feat(oss):添加ucloud

backend/pom.xml, backend/src/main/java/com/hummerrisk/proxy/baidu/BaiduRequest.java, backend/src/main/java/com/hummerrisk/service/CloudEventService.java
=> feat(event):添加火山云

backend/src/main/java/com/hummerrisk/controller/CloudResourceController.java
=> feat(resource):添加summary接口

frontend/src/business/components/event/home/Sync.vue, frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
Fixes # .
调整日期范围宽度，新增最近两周快捷选择，新增event相关翻译
-
-
=> feat(event):调整日期范围宽度，新增最近两周快捷选择，新增event相关翻译

backend/src/main/java/com/hummerrisk/service/CloudEventService.java
=> feat(event):解决火山区域同步数据数量重复问题

backend/src/main/java/com/hummerrisk/oss/provider/QingcloudProvider.java
=> feat(oss):修改青云bucket

backend/pom.xml
=> feat(pom):添加jakarta相关依赖

backend/src/main/java/com/hummerrisk/oss/provider/QiniuProvider.java
=> feat(oss):添加七牛创建文件夹功能

frontend/src/business/components/rule/home/Rule.vue
=> fix(rule):解决云资源检测规则切换标签后点击搜索标签失效问题

frontend/src/business/components/vuln/home/Rule.vue
=> fix(rule):解决漏洞检测规则切换标签后点击搜索标签失效问题

backend/src/main/java/com/hummerrisk/oss/provider/QingcloudProvider.java, backend/src/main/java/com/hummerrisk/oss/provider/QiniuProvider.java, backend/src/main/resources/support/regions/hummer-qiniu-plugin.json
=> fix(oss):处理青云七牛bucket创建报错问题

backend/src/main/java/com/hummerrisk/oss/provider/QingcloudProvider.java, backend/src/main/java/com/hummerrisk/oss/service/OssService.java, backend/src/main/java/com/hummerrisk/service/CloudEventService.java
=> feat(oss):修改青云创建和删除存储桶

backend/pom.xml
=> feat(pom):新增京东云sdk

backend/pom.xml, backend/src/main/java/com/hummerrisk/commons/constants/RegionsConstants.java, backend/src/main/java/com/hummerrisk/commons/utils/PlatformUtils.java, backend/src/main/java/com/hummerrisk/proxy/jdcloud/JDCloudCredential.java, backend/src/main/java/com/hummerrisk/proxy/jdcloud/JDRequest.java
=> feat(PlatformUtils):增加京东云

backend/src/main/resources/db/migration/V40__init_webhook.sql
=> feat(flyway):新增京东云插件

backend/src/main/resources/db/migration/V40__init_webhook.sql
=> feat(flyway):新增京东云检测规则

backend/src/main/resources/db/migration/V40__init_webhook.sql
=> feat(flyway):修改七牛云对象存储资源名称 Kodo

backend/src/main/java/com/hummerrisk/commons/constants/CloudTaskConstants.java, backend/src/main/java/com/hummerrisk/commons/utils/PlatformUtils.java
=> feat(jdcloud):修改PlatformUtils

backend/src/main/resources/db/migration/V40__init_webhook.sql
=> feat(flyway):增加青云对象存储检测

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudEventMapper.java, backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudEventMapper.xml, backend/src/main/java/com/hummerrisk/dto/CloudEventSourceIpInsightDto.java, frontend/src/business/components/event/head/LogHeaderMenus.vue
=> feat(event):增加源ip分析

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudEventMapper.xml, backend/src/main/java/com/hummerrisk/controller/CloudEventController.java, backend/src/main/java/com/hummerrisk/dto/CloudEventSourceIpInsightDto.java, backend/src/main/java/com/hummerrisk/service/CloudEventService.java, frontend/src/business/components/event/home/Ip.vue, frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
=> feat(event):源地址分析修改

frontend/src/business/components/event/home/Ip.vue
=> feat(event):调整table宽度

frontend/src/business/components/event/home/Ip.vue
=> feat(event):添加详情

frontend/src/business/components/event/home/Ip.vue, frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
=> feat(event):修改ip分析

backend/pom.xml, backend/src/main/java/com/hummerrisk/commons/constants/CloudTaskConstants.java, backend/src/main/java/com/hummerrisk/commons/constants/RegionsConstants.java, backend/src/main/java/com/hummerrisk/commons/utils/PlatformUtils.java, backend/src/main/java/com/hummerrisk/proxy/ksyun/KsyunCredential.java, backend/src/main/java/com/hummerrisk/proxy/ksyun/KsyunRequest.java
=> feat(cloud):增加金山云

backend/src/main/resources/db/migration/V41__alter_k8s.sql
=> feat(flyway):增加金山云插件

backend/src/main/resources/db/migration/V41__alter_k8s.sql
=> feat(flyway):增加金山云规则

backend/src/main/java/com/hummerrisk/commons/constants/CloudTaskConstants.java
=> feat(resource):增加金山云资源类型

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudEventMapper.java, backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudEventMapper.xml, backend/src/main/java/com/hummerrisk/commons/utils/DateUtils.java, backend/src/main/java/com/hummerrisk/controller/CloudEventController.java, backend/src/main/java/com/hummerrisk/service/CloudEventService.java
=> feat(cloudEvent):新增 ip 统计图表后端接口

frontend/src/business/components/event/head/IpChart.vue
=> fix(cloudEvent):解决 ip 统计显示八天问题

backend/src/main/java/com/hummerrisk/commons/utils/DateUtils.java, backend/src/main/java/com/hummerrisk/service/CloudEventService.java
=> fix(cloudEvent):后端新增金山云事件同步

backend/src/main/java/com/hummerrisk/service/CloudEventService.java, frontend/src/business/components/event/home/Sync.vue
=> feat(cloudEvent):修改金山云事件同步

backend/src/main/java/com/hummerrisk/oss/config/OssManager.java, backend/src/main/java/com/hummerrisk/oss/constants/OSSConstants.java, backend/src/main/java/com/hummerrisk/oss/provider/JdcloudProvider.java, backend/src/main/java/com/hummerrisk/oss/service/OssService.java, backend/src/main/resources/support/regions/hummer-jdcloud-plugin.json
=> feat(oss):增加京东云对象存储

backend/src/main/java/com/hummerrisk/oss/provider/JdcloudProvider.java
=> feat(oss):修改京东云对象存储

frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
=> feat(i18n):增加操作审计相关翻译

backend/src/main/java/com/hummerrisk/oss/provider/JdcloudProvider.java
=> fix(OSS):解决京东云创建目录报错问题

backend/src/main/resources/db/migration/V42__init_image_repo_setting.sql
=> feat(flyway):增加京东对象存储相关规则及青云和七牛云对象存储规则组

backend/src/main/java/com/hummerrisk/commons/utils/DateUtils.java
=> feat(DateUtils):修改 UTC 时间转换

frontend/src/business/components/cloudSituation/home/ResourceRule.vue
=> fix(resource):解决有风险资源跳转检测结果云账号选择错误问题

backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudResourceItemMapper.java, backend/src/main/java/com/hummerrisk/base/mapper/ext/ExtCloudResourceItemMapper.xml, backend/src/main/java/com/hummerrisk/service/CloudResourceService.java
=> perf(resource):提高资源态势查询速度

backend/src/main/java/com/hummerrisk/service/SystemParameterService.java
=> fix(vuln):解决离线漏洞库上传失败问题

backend/pom.xml, backend/src/main/java/com/hummerrisk/proxy/baidu/BaiduRequest.java, backend/src/main/java/com/hummerrisk/proxy/baidu/QueryEventResponse.java, backend/src/main/java/com/hummerrisk/service/CloudEventService.java
=> feat(event):操作审计增加百度云

frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
=> feat(i18n):新增翻译

backend/pom.xml, backend/src/main/java/com/hummerrisk/commons/utils/PlatformUtils.java
=> fix(result):解决百度云和青云翻译问题，增加 httpclient

backend/src/main/java/com/hummerrisk/oss/provider/BaiduProvider.java, backend/src/main/java/com/hummerrisk/proxy/baidu/BaiduRequest.java
=> fix(result):解决百度云对象存储报错 bug

backend/src/main/java/com/hummerrisk/commons/constants/RegionsConstants.java, backend/src/main/java/com/hummerrisk/commons/utils/PlatformUtils.java, frontend/src/business/components/event/home/Sync.vue, frontend/src/i18n/en-US.js, frontend/src/i18n/zh-CN.js, frontend/src/i18n/zh-TW.js
=> fix(baidu):解决百度云新加坡报错及下拉框区域有 default 问题

frontend/src/business/components/event/home/Sync.vue
=> fix(event):解决事件跳转问题

backend/src/main/java/com/hummerrisk/service/AccountService.java
=> fix(event):解决删除云账号后事件不删除bug

pom.xml
=> fix(gateway):解决启动报错问题

backend/pom.xml
=> fix(pom): Lombok compilation failed to load

backend/src/main/java/com/hummerrisk/proxy/k8s/K8sRequest.java, backend/src/main/java/com/hummerrisk/service/K8sService.java
=> refactor(k8s): fix exception prompt

backend/src/main/java/com/hummerrisk/proxy/k8s/K8sRequest.java, backend/src/main/java/com/hummerrisk/service/K8sService.java
=> refactor(k8s): add hummer ChartRepo and trivy-operator

backend/src/main/java/com/hummerrisk/proxy/k8s/K8sRequest.java
=> refactor(k8s): remove useless imports

pom.xml
=> fix(pom):解决服务无法注入 nacos 问题

backend/src/main/java/com/hummerrisk/oss/provider/QcloudProvider.java, backend/src/main/java/com/hummerrisk/oss/service/OssService.java
Fixes # .
https://github.com/HummerRisk/HummerRisk/issues/155
=> refactor(bucket): update bucket size and number

hummer-auth/pom.xml, hummer-auth/src/main/java/com/hummer/auth/AuthApplication.java, hummer-auth/src/main/java/com/hummer/auth/config/MybatisConfig.java, hummer-auth/src/main/java/com/hummer/auth/service/UserService.java
=> feat(auth):解决mapper为空问题

hummer-auth/src/main/java/com/hummer/auth/controller/LoginController.java, hummer-auth/src/main/resources/bootstrap.yml, hummer-common/hummer-common-security/src/main/java/com/hummer/common/security/utils/SecurityUtils.java, hummer-ui/src/common/js/ajax.js, hummer-ui/src/common/js/utils.js, hummer-ui/src/login/Login.vue, hummer-ui/vue.config.js
=> feat(login):修改登录认证

frontend/src/business/components/event/home/RegionLog.vue
=> feat(event):增加翻译

backend/src/main/java/com/hummerrisk/commons/utils/PlatformUtils.java, backend/src/main/java/com/hummerrisk/service/AccountService.java, frontend/src/business/components/cloudSituation/home/CloudModule.vue
=> feat(cloudSituation):不同步 k8s 资源

hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/service/RuleService.java, hummer-modules/hummer-cloud/src/main/resources/bootstrap.yml, hummer-modules/hummer-k8s/src/main/resources/bootstrap.yml, hummer-modules/hummer-system/src/main/resources/bootstrap.yml
=> feat(dubbo):修改 dubbo 相关配置及注解

hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/UserController.java, hummer-ui/src/business/components/common/head/LanguageSwitch.vue, hummer-ui/src/i18n/i18n.js
=> fix(i18n):解决切换语言后语言不变问题

hummer-modules/hummer-cloud/src/main/resources/bootstrap.yml, hummer-modules/hummer-k8s/src/main/resources/bootstrap.yml, hummer-modules/hummer-system/src/main/resources/bootstrap.yml
=> feat(dubbo):解决 gateway 调用间歇性失败问题。

hummer-ui/src/business/components/event/home/RegionLog.vue
=> feat(event):修改翻译

hummer-common/hummer-common-core/src/main/java/com/hummer/common/core/domain/RuleGroupMappingExample.java
=> feat(example):子类实现序列化接口

hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/CloudTaskController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/mapper/ext/ExtRuleMapper.xml, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/service/ResourceCreateService.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/service/ResourceService.java
=> feat(cloudTask):解决检测云检测没有数据问题

hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/CloudTaskController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/service/AccountService.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/service/CloudSyncService.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/service/ResourceService.java, hummer-ui/src/api/cloud/resource/resource.js
=> feat(cloudResource):解决云资源列表显示问题

hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/service/CloudEventService.java
=> feat(event):腾讯云操作审计增加资源信息

hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/service/CloudEventService.java
=> feat(event):解决操作审计报错

hummer-gateway/src/main/resources/bootstrap.yml, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/CloudTaskController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/oss/provider/HuaweiProvider.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/service/OssService.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/service/ResourceCreateService.java
=> feat(gateway):日志级别改为 trace

hummer-ui/src/api/cloud/account/account.js, hummer-ui/src/business/components/cloudSituation/home/SourceList.vue
=> feat(resource):解决云资源显示问题

hummer-common/hummer-common-core/src/main/java/com/hummer/common/core/utils/PlatformUtils.java
=> feat(k8s):修改 region 获取代码

hummer-ui/src/business/components/common/head/HeaderUser.vue
=> feat(api):增加 api 文档链接

hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/AccountController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/CloudEventController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/CloudSyncController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/OssController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/ResourceController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/RuleController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/TagController.java, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/controller/CodeController.java, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/controller/ConfigController.java, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/controller/FileSystemController.java, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/controller/ImageController.java, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/controller/K8sController.java, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/controller/SbomController.java, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/controller/ServerController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/DashboardController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/HistoryController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/OperationLogController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/PluginController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/ProxyController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/RoleController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/SystemParameterController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/UserController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/UserKeysController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/WebMsgController.java
=> feat(knife4f):增加 openApi3 注解

hummer-common/hummer-common-core/src/main/java/com/hummer/common/core/utils/CommandUtils.java
=> fix(cloud):解决 str is null 报错

hummer-auth/src/main/resources/db/migration/V45__alter_rule.sql
=> feat(flyway):新增 aliyun 3 条规则

hummer-auth/src/main/java/com/hummer/auth/controller/LoginController.java, hummer-common/hummer-common-core/src/main/java/com/hummer/common/core/handler/ResultHolder.java, hummer-gateway/src/main/java/com/hummer/gateway/controller/LoginController.java, hummer-gateway/src/main/resources/bootstrap.yml, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/AccountController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/CloudResourceController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/CloudTaskController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/IndexController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/OssController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/ResourceController.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/RuleController.java, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/controller/CodeController.java, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/controller/ConfigController.java, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/controller/FileSystemController.java, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/controller/ImageController.java, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/controller/IndexController.java, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/controller/K8sController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/HelloController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/HistoryController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/IndexController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/NoticeController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/UserController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/UserKeysController.java, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/UserRoleController.java
=> feat(knife4j):增加 Hidden 注解

hummer-modules/hummer-cloud/src/main/resources/bootstrap.yml, hummer-modules/hummer-k8s/src/main/resources/bootstrap.yml, hummer-modules/hummer-system/src/main/resources/bootstrap.yml
=> feat(dubbo):加大超时时间

hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/mapper/ext/ExtCloudTaskMapper.java, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/mapper/ext/ExtCloudTaskMapper.xml
=> fix(resource):解决资源态势列表中，点击资源的风险按钮，显示内容是空问题

hummer-auth/src/main/resources/db/migration/V45__alter_rule.sql
=> feat(flyway):增加 ECS 白名单规则

hummer-common/hummer-common-core/src/main/java/com/hummer/common/core/utils/PlatformUtils.java
=> feat(platform):增加 rancher 和 kubeshpere

hummer-common/hummer-common-core/pom.xml, hummer-common/hummer-common-core/src/main/java/com/hummer/common/core/utils/PlatformUtils.java
=> fix(cloudAccount):解决百度、青云、七牛、ucloud 账号 ak/sk 状态认证问题

hummer-common/hummer-common-core/pom.xml, hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/service/ImageService.java
=> feat(imageRepo):新增腾讯云镜像同步

hummer-auth/src/main/resources/db/migration/V47__init_image_group.sql
=> feat(flyway):image repo 新增 account_id 字段

hummer-gateway/pom.xml, hummer-gateway/src/main/java/com/hummer/gateway/GatewayApplication.java, hummer-gateway/src/main/java/com/hummer/gateway/filter/AuthFilter.java, hummer-gateway/src/main/java/com/hummer/gateway/mapper/UserKeyMapper.java, hummer-gateway/src/main/java/com/hummer/gateway/mapper/UserKeyMapper.xml, hummer-gateway/src/main/java/com/hummer/gateway/service/ApiKeyService.java, hummer-gateway/src/main/resources/bootstrap.yml, hummer-modules/hummer-system/src/main/java/com/hummer/system/controller/UserKeysController.java, hummer-ui/src/api/system/system.js, hummer-ui/src/business/components/settings/personal/ApiKeys.vue, hummer-ui/src/i18n/en-US.js, hummer-ui/src/i18n/zh-CN.js, hummer-ui/src/i18n/zh-TW.js
=> feat(apiKey):增加 apiKey 认证

hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/controller/TestScanerController.java
=> feat(scanner):增加测试接口  @wangjiankun233

hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/service/ImageService.java
=> feat(image):aws 增加仓库地址

hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/service/ImageService.java
=> feat(image):aws 增加中国区同步，增加私有仓库同步

hummer-modules/hummer-k8s/src/main/java/com/hummer/k8s/service/ImageService.java
=> feat(image):aws 增加所有区域私有仓库同步

hummer-common/hummer-common-core/src/main/java/com/hummer/common/core/utils/PlatformUtils.java
=> feat(cloudResource):tencent.mongodb 增加不支持资源区域

hummer-common/hummer-common-core/pom.xml, hummer-modules/hummer-cloud/src/main/java/com/hummer/cloud/service/CloudEventService.java
=> feat(event):更新 aliyun 操作审计 sdk 解决操作审计无法同步问题

hummer-common/hummer-common-core/pom.xml, hummer-modules/hummer-cloud/pom.xml
=> feat(maven):修改操作审计依赖到 cloud 模块下
